apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepak-rapidfort-assignment-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: deepak258/deepakrapidfort:latest
          ports:
            - containerPort: 5050