apiVersion: v1
kind: Service
metadata:
  name: deepak-rapidfort-assignment-service
spec:
  selector:
    app: server
  type: NodePort
  ports:
    - protocol: TCP 
      port: 5050
      targetPort: 5050
      nodePort : 30004